### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by ryanpag3** [cloudaper/epics-action#11]
Hey there, 

Just stumbled upon this action and noticed that if I include the new `auto-close-epic` option the `v1.0.2` version doesn't have it.

```
Warning: Unexpected input(s) 'auto-close-epic', valid inputs are ['github-token', 'epic-label-name']
```

Any chance you can cut a new release?

**Comment by krystof-k** [comment]
Hey @ryanpag3, sorry! Sure, working on it.

**Comment by ryanpag3** [comment]
No worries! Thanks 😄

**Comment by krystof-k** [comment]
Done. I also finally set up the CI so new releases should be piece of cake.
