### ISSUE TITLE
Auto-closing closes even when other to do items are not finished

### ISSUE THREAD

**Issue by krystof-k** [cloudaper/epics-action#23]

**Comment by rrsettgast** [comment]
I have this issue as well. I just started using the action, and made a tests sub-issue in my epic list of issues. Manually closed the sub-issue, and the epic closed through the action.

**Comment by krystof-k** [comment]
@rrsettgast I'll try to look into that as soon as possible.

**Comment by krystof-k** [comment]
Well, sorry @rrsettgast, year is not exactly ASAP, but finally done.
