### ISSUE TITLE
Where do i find epic task list?

### ISSUE THREAD

**Issue by tst32** [cloudaper/epics-action#28]
cloudaper/epics-action@v1
it run but nothing ...

**Comment by krystof-k** [comment]
Sorry, I don't understand where is the problem.

**Comment by tst32** [comment]
Pardon, me so brief 😸  done adding epic.yml to actions i was expected that the a some todo list was produced. but nothung happened after epic.yml execution all issues labeled 'epic' remained the same. Where is todo list? 
![image](https://user-images.githubusercontent.com/23115742/127634374-4e3dcd14-4be7-4fcc-9ff0-4460e5fd9e58.png)

**Comment by krystof-k** [comment]
It will just update the checkboxes when the issue referenced is closed/open, it does not create any list.

**Comment by tst32** [comment]
OK, got it!
Rozumím, díky.
