### ISSUE TITLE
Update README.md with information about task lists

### ISSUE THREAD

**Issue by krystof-k** [cloudaper/epics-action#30]
The action is basically unnecessary as it does the same thing as native [task lists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) now.

**Comment by aka-bash0r** [comment]
@krystof-k the action closes referenced epics automatically as soon as all referenced issues are closed. The task list does not appear to do this natively.

**Comment by krystof-k** [comment]
Also note the even better [new beta](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists).
