### ISSUE TITLE
Don't throw error when issue is deleted

### ISSUE THREAD

**Issue by krystof-k** [cloudaper/epics-action#6]

**Comment by renestefancic** [comment]
Any ETA on this?

**Comment by krystof-k** [comment]
I'll try to push it forward soon!

**Comment by renestefancic** [comment]
Thank you! Appreciate your work.

**Comment by krystof-k** [comment]
Done. However it will not check the issue mentioned in the epic – it would require to completely rework how the action works and I'm not sure whether it would even be desired behavior.

**Comment by renestefancic** [comment]
I keep getting the error

```
Error: TypeError: Cannot read property 'number' of undefined
Error: Cannot read property 'number' of undefined
```

Which I assume is thrown when issues are deleted. In my case, both the epic (parent) and issues referenced in the epic were deleted.

**Comment by krystof-k** [comment]
I see – it probably hasn't fixed when epic is deleted. Reopening and I'll look further into that.

**Comment by krystof-k** [comment]
I wasn't able to replicate it. It works fine when both the issue or the epic is deleted.

**Comment by renestefancic** [comment]
I was also not able to replicate it after further testing.

Interestingly enough, it's now working properly and is no longer throwing any errors.

This can probably be closed.
